//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foustiga.WPF.Scheduler.Assets {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foustiga.WPF.Scheduler.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Every.
        /// </summary>
        public static string Daily_Every {
            get {
                return ResourceManager.GetString("Daily_Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à day(s).
        /// </summary>
        public static string Daily_Every_day_s {
            get {
                return ResourceManager.GetString("Daily_Every_day_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Every weekday.
        /// </summary>
        public static string Daily_EveryWeekday {
            get {
                return ResourceManager.GetString("Daily_EveryWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à April.
        /// </summary>
        public static string Enum_Month_April {
            get {
                return ResourceManager.GetString("Enum_Month_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à August.
        /// </summary>
        public static string Enum_Month_August {
            get {
                return ResourceManager.GetString("Enum_Month_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à December.
        /// </summary>
        public static string Enum_Month_December {
            get {
                return ResourceManager.GetString("Enum_Month_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à February.
        /// </summary>
        public static string Enum_Month_February {
            get {
                return ResourceManager.GetString("Enum_Month_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à January.
        /// </summary>
        public static string Enum_Month_January {
            get {
                return ResourceManager.GetString("Enum_Month_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à July.
        /// </summary>
        public static string Enum_Month_July {
            get {
                return ResourceManager.GetString("Enum_Month_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à June.
        /// </summary>
        public static string Enum_Month_June {
            get {
                return ResourceManager.GetString("Enum_Month_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à March.
        /// </summary>
        public static string Enum_Month_March {
            get {
                return ResourceManager.GetString("Enum_Month_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à May.
        /// </summary>
        public static string Enum_Month_May {
            get {
                return ResourceManager.GetString("Enum_Month_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à November.
        /// </summary>
        public static string Enum_Month_November {
            get {
                return ResourceManager.GetString("Enum_Month_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à October.
        /// </summary>
        public static string Enum_Month_October {
            get {
                return ResourceManager.GetString("Enum_Month_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à September.
        /// </summary>
        public static string Enum_Month_September {
            get {
                return ResourceManager.GetString("Enum_Month_September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Daily.
        /// </summary>
        public static string Enum_ReccurrenceType_Daily {
            get {
                return ResourceManager.GetString("Enum_ReccurrenceType_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Occurernces to be calculated on daily base. .
        /// </summary>
        public static string Enum_ReccurrenceType_Daily_Tooltip {
            get {
                return ResourceManager.GetString("Enum_ReccurrenceType_Daily_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Monthly.
        /// </summary>
        public static string Enum_ReccurrenceType_Monthly {
            get {
                return ResourceManager.GetString("Enum_ReccurrenceType_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Occurernces to be calculated on monthly base. .
        /// </summary>
        public static string Enum_ReccurrenceType_Monthly_Tooltip {
            get {
                return ResourceManager.GetString("Enum_ReccurrenceType_Monthly_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Weekly.
        /// </summary>
        public static string Enum_ReccurrenceType_Weekly {
            get {
                return ResourceManager.GetString("Enum_ReccurrenceType_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Occurernces to be calculated on weekly base. .
        /// </summary>
        public static string Enum_ReccurrenceType_Weekly_Tooltip {
            get {
                return ResourceManager.GetString("Enum_ReccurrenceType_Weekly_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yearly.
        /// </summary>
        public static string Enum_ReccurrenceType_Yearly {
            get {
                return ResourceManager.GetString("Enum_ReccurrenceType_Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Occurernces to be calculated on yearly base. .
        /// </summary>
        public static string Enum_ReccurrenceType_Yearly_Tooltip {
            get {
                return ResourceManager.GetString("Enum_ReccurrenceType_Yearly_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Every day.
        /// </summary>
        public static string Enum_WeekDays_EveryDay {
            get {
                return ResourceManager.GetString("Enum_WeekDays_EveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Friday.
        /// </summary>
        public static string Enum_WeekDays_Friday {
            get {
                return ResourceManager.GetString("Enum_WeekDays_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Monday.
        /// </summary>
        public static string Enum_WeekDays_Monday {
            get {
                return ResourceManager.GetString("Enum_WeekDays_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saturday.
        /// </summary>
        public static string Enum_WeekDays_Saturday {
            get {
                return ResourceManager.GetString("Enum_WeekDays_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sunday.
        /// </summary>
        public static string Enum_WeekDays_Sunday {
            get {
                return ResourceManager.GetString("Enum_WeekDays_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thursday.
        /// </summary>
        public static string Enum_WeekDays_Thursday {
            get {
                return ResourceManager.GetString("Enum_WeekDays_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tuesday.
        /// </summary>
        public static string Enum_WeekDays_Tuesday {
            get {
                return ResourceManager.GetString("Enum_WeekDays_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wednesday.
        /// </summary>
        public static string Enum_WeekDays_Wednesday {
            get {
                return ResourceManager.GetString("Enum_WeekDays_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Weekend days.
        /// </summary>
        public static string Enum_WeekDays_WeekendDays {
            get {
                return ResourceManager.GetString("Enum_WeekDays_WeekendDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Workd days.
        /// </summary>
        public static string Enum_WeekDays_WorkDays {
            get {
                return ResourceManager.GetString("Enum_WeekDays_WorkDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First.
        /// </summary>
        public static string Enum_WeekOfMonth_First {
            get {
                return ResourceManager.GetString("Enum_WeekOfMonth_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fourth.
        /// </summary>
        public static string Enum_WeekOfMonth_Fourth {
            get {
                return ResourceManager.GetString("Enum_WeekOfMonth_Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last.
        /// </summary>
        public static string Enum_WeekOfMonth_Last {
            get {
                return ResourceManager.GetString("Enum_WeekOfMonth_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        public static string Enum_WeekOfMonth_None {
            get {
                return ResourceManager.GetString("Enum_WeekOfMonth_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Second.
        /// </summary>
        public static string Enum_WeekOfMonth_Second {
            get {
                return ResourceManager.GetString("Enum_WeekOfMonth_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Third.
        /// </summary>
        public static string Enum_WeekOfMonth_Third {
            get {
                return ResourceManager.GetString("Enum_WeekOfMonth_Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Day.
        /// </summary>
        public static string Monthly_None_Day {
            get {
                return ResourceManager.GetString("Monthly_None_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à month(s).
        /// </summary>
        public static string Monthly_None_month {
            get {
                return ResourceManager.GetString("Monthly_None_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à of every.
        /// </summary>
        public static string Monthly_None_OfEvery {
            get {
                return ResourceManager.GetString("Monthly_None_OfEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The.
        /// </summary>
        public static string Monthly_The {
            get {
                return ResourceManager.GetString("Monthly_The", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à of every.
        /// </summary>
        public static string Monthly_The_OfEvery {
            get {
                return ResourceManager.GetString("Monthly_The_OfEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End after:.
        /// </summary>
        public static string Range_EndAfter {
            get {
                return ResourceManager.GetString("Range_EndAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à occurrences.
        /// </summary>
        public static string Range_EndAfter_Occurrences {
            get {
                return ResourceManager.GetString("Range_EndAfter_Occurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End by:.
        /// </summary>
        public static string Range_EndBy {
            get {
                return ResourceManager.GetString("Range_EndBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No end date.
        /// </summary>
        public static string Range_NoEndDate {
            get {
                return ResourceManager.GetString("Range_NoEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start after:.
        /// </summary>
        public static string Range_StartAfter {
            get {
                return ResourceManager.GetString("Range_StartAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Range of recurrence.
        /// </summary>
        public static string RangeOfRecurrence {
            get {
                return ResourceManager.GetString("RangeOfRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recurrence pattern.
        /// </summary>
        public static string Recurrence_pattern {
            get {
                return ResourceManager.GetString("Recurrence_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Neutral text.
        /// </summary>
        public static string tst {
            get {
                return ResourceManager.GetString("tst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Friday.
        /// </summary>
        public static string Weekly_Friday {
            get {
                return ResourceManager.GetString("Weekly_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Monday.
        /// </summary>
        public static string Weekly_Monday {
            get {
                return ResourceManager.GetString("Weekly_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recur every.
        /// </summary>
        public static string Weekly_RecurEvery {
            get {
                return ResourceManager.GetString("Weekly_RecurEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à week(s) on:.
        /// </summary>
        public static string Weekly_RecurEvery_WeekOn {
            get {
                return ResourceManager.GetString("Weekly_RecurEvery_WeekOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saturday.
        /// </summary>
        public static string Weekly_Saturday {
            get {
                return ResourceManager.GetString("Weekly_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sunday.
        /// </summary>
        public static string Weekly_Sunday {
            get {
                return ResourceManager.GetString("Weekly_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thursday.
        /// </summary>
        public static string Weekly_Thursday {
            get {
                return ResourceManager.GetString("Weekly_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tuesday.
        /// </summary>
        public static string Weekly_Tuesday {
            get {
                return ResourceManager.GetString("Weekly_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wednesday.
        /// </summary>
        public static string Weekly_Wedenesday {
            get {
                return ResourceManager.GetString("Weekly_Wedenesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Every.
        /// </summary>
        public static string Yearly_None {
            get {
                return ResourceManager.GetString("Yearly_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The.
        /// </summary>
        public static string Yearly_The {
            get {
                return ResourceManager.GetString("Yearly_The", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à of.
        /// </summary>
        public static string Yearly_The_of {
            get {
                return ResourceManager.GetString("Yearly_The_of", resourceCulture);
            }
        }
    }
}
